---
title: "Visium Part I processing"
author: "Chaoyang Ye"
date: "2024-08-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(Giotto)
```

Set instructions
```{r}
results_folder <- "/Users/chaoyangye/Documents/Giotto workshop/results/01_session5"

python_path <- "/usr/bin/python3" # need to install igraph, pandas, leidenalg, 
# networkx, sklearn, python-louvain modules under python

instructions <- createGiottoInstructions(
  save_dir = results_folder,
  save_plot = TRUE,
  show_plot = FALSE,
  return_plot = FALSE,
  python_path = python_path
)
```

create object
```{r}
## Provide the path to the visium folder
data_path <- "/Users/chaoyangye/Documents/Giotto workshop/data/01_session5"

## Create object directly from the visium folder
visium_brain <- createGiottoVisiumObject(
  visium_dir = data_path,
  expr_data = "raw",
  png_name = "tissue_lowres_image.png",
  gene_column_index = 2,
  instructions = instructions
)

```
```{r}
pDataDT(gobject = visium_brain) # look at the data
```

initial image
```{r}
spatPlot2D(
  gobject = visium_brain,
  cell_color = "in_tissue",
  point_size = 2,
  cell_color_code = c("0" = "lightgrey", "1" = "blue"),
  show_image = TRUE)
```

metadata related to spatial info
```{r}
metadata <- getCellMetadata(gobject = visium_brain,
                            output = "data.table")
metadata
```

filter for only cells within tissue
```{r}
in_tissue_barcodes <- metadata[in_tissue == 1]$cell_ID

visium_brain <- subsetGiotto(gobject = visium_brain,
                             cell_ids = in_tissue_barcodes)

visium_brain_statistics <- addStatistics(gobject = visium_brain,
                                         expression_values = "raw")

```

filtering parameter test
```{r}
spatPlot2D(gobject = visium_brain_statistics, 
           cell_color = "nr_feats", 
           color_as_factor = FALSE)
filterDistributions(gobject = visium_brain_statistics, 
                    detection = "cells") # number of features detected per cell distribution
filterDistributions(gobject = visium_brain_statistics, 
                    detection = "feats") # number of cells containing certain number of features distribution
filterCombinations(gobject = visium_brain_statistics,
                   expression_thresholds = c(1, 2, 3),
                   feat_det_in_min_cells = c(50, 100, 200),
                   min_det_feats_per_cell = c(500, 1000, 1500))
visium_brain <- filterGiotto(
  gobject = visium_brain,
  expression_threshold = 1,
  feat_det_in_min_cells = 50,
  min_det_feats_per_cell = 1000,
  expression_values = "raw",
  verbose = TRUE
)
showGiottoExpression(visium_brain)

```
normalization
```{r}
visium_brain <- normalizeGiotto(
  gobject = visium_brain,
  scalefactor = 6000,
  verbose = TRUE
)
visium_brain <- addStatistics(gobject = visium_brain)

## plot
spatPlot2D(gobject = visium_brain, 
           cell_color = "nr_feats", # saved @cell_metadata
           color_as_factor = FALSE)
spatPlot2D(gobject = visium_brain, 
           cell_color = "total_expr", 
           color_as_factor = FALSE)

```
identify highly variable features
```{r}
visium_brain <- calculateHVF(gobject = visium_brain, 
                             method = "cov_loess",
                             save_plot = TRUE,
                             default_save_name = "HVFplot_loess")
options(future.globals.maxSize = Inf) # reset value to rid of error msg
visium_brain <- calculateHVF(gobject = visium_brain, 
                             method = "var_p_resid", # highly variable genes, not the best method
                             save_plot = TRUE,
                             default_save_name = "HVFplot_pearson")
visium_brain <- calculateHVF(gobject = visium_brain, 
                             method = "cov_groups", # good for when not knowing the distribution
                             save_plot = TRUE,
                             default_save_name = "HVFplot_binned")

```

PCA
```{r}
visium_brain <- runPCA(gobject = visium_brain)
my_features <- head(getFeatureMetadata(visium_brain, 
                                       output = "data.table")$feat_ID, 
                    1000)
visium_brain <- runPCA(gobject = visium_brain,
                       feats_to_use = my_features,
                       name = "custom_pca") # use less features
screePlot(gobject = visium_brain, 
          ncp = 30)
plotPCA(gobject = visium_brain)
plotPCA(gobject = visium_brain,
        dim_reduction_name = "custom_pca")

```
clustering
```{r}
visium_brain <- runUMAP(visium_brain, 
                        dimensions_to_use = 1:10)
plotUMAP(gobject = visium_brain)

visium_brain <- runtSNE(gobject = visium_brain, 
                        dimensions_to_use = 1:10)
plotTSNE(gobject = visium_brain)

```

network analysis
```{r}
visium_brain <- createNearestNetwork(gobject = visium_brain, 
                                     dimensions_to_use = 1:10, 
                                     k = 15) # shared nearest neighbor 
visium_brain <- createNearestNetwork(gobject = visium_brain, 
                                     dimensions_to_use = 1:10, 
                                     k = 15,
                                     type = "kNN")
slotNames(visium_brain)

```
From network analysis identify clusters
```{r}
visium_brain <- doLeidenCluster(gobject = visium_brain, 
                                resolution = 0.4, 
                                n_iterations = 1000)
plotUMAP(gobject = visium_brain,
         cell_color = "leiden_clus", 
         show_NN_network = FALSE, 
         point_size = 2.5)
plotUMAP(gobject = visium_brain,
         cell_color = "leiden_clus", 
         show_NN_network = TRUE, 
         point_size = 2.5)
plotTSNE(gobject = visium_brain,
         cell_color = "leiden_clus",
         point_size = 2.5,
         show_NN_network = TRUE)
spatPlot2D(visium_brain, 
           cell_color = "leiden_clus",
           point_size = 3)

# louvain clustering for large networks
# need to install python-louvain module
visium_brain <- doLouvainCluster(visium_brain)
spatPlot2D(visium_brain, 
           cell_color = "louvain_clus")

saveGiotto(visium_brain, 
           foldername = "visium_brain_object",
           dir = "/Users/chaoyangye/Documents/Giotto workshop/results/01_session5",
           overwrite = T)

```

